### ISSUE TITLE
Add minimum token permissions for all github workflow files

### ISSUE THREAD

**Issue by opentelemetrybot** [opentelemetrybot/opentelemetry-java-contrib#41]
Add minimum token permissions for all GitHub workflow files to improve security posture according to OpenSSF Scorecard recommendations.

## Context
This addresses the Token-Permissions check from https://github.com/ossf/scorecard/blob/ab2f6e92482462fe66246d9e32f642855a691dc1/docs/checks.md#token-permissions.

## 🎯 Primary Objective: Add Root-Level Permissions

Every workflow file MUST have a root-level `permissions:` YAML block.

### Rules for Root-Level Permission Block:
1. **🔍 READ THE FILE FIRST**: Always examine the existing formatting style before making any changes
2. Root-Level permissions MUST be limited to either `read-all` or `contents: read`
3. If existing root-level permissions have more permissions, then move the root-level permission down to the job level
4. **Standard format**: New root-level permissions should be:
   ```yaml
   permissions:
     contents: read
   ```
5. **Placement**: Insert immediately after the root-level `on:` YAML block (no other blocks in between)
6. **Don't reorder existing blocks** - only add the permissions block
7. **Preserve formatting**: Match the existing blank line style (see detailed rules below)

### Blank Line Formatting Rules:
**⚠️ MOST COMMON MISTAKE**: Not reading the original file to check blank line style before making changes.

**🔍 STEP 1 - ALWAYS DO THIS FIRST**: Read the entire workflow file and look at the spacing after the `on:` block.

**Case 1 - Compact style (NO blank line after `on:` block)**:
```yaml
on:
  workflow_dispatch:
jobs:  # ← Notice: jobs starts immediately after on: block
```
**✅ CORRECT** - Add permissions with NO blank lines:
```yaml
on:
  workflow_dispatch:
permissions:  # ← No blank line above
  contents: read
jobs:  # ← No blank line below
```

**❌ WRONG** - Don't add blank lines in compact style:
```yaml
on:
  workflow_dispatch:

permissions:  # ← WRONG: blank line added
  contents: read

jobs:  # ← WRONG: blank line added
```

**Case 2 - Spaced style (WITH blank line after `on:` block)**:
```yaml
on:
  workflow_dispatch:
  # ← Notice: blank line here
jobs:
```
**✅ CORRECT** - Add permissions with blank lines above AND below:
```yaml
on:
  workflow_dispatch:
  # ← Existing blank line preserved
permissions:  # ← No additional blank line above
  contents: read
  # ← Blank line added below
jobs:
```

**❌ WRONG** - Don't skip blank lines in spaced style:
```yaml
on:
  workflow_dispatch:

permissions:  # ← WRONG: no blank line below
  contents: read
jobs:  # ← WRONG: should have blank line above
```

## 🔒 Secondary Objective: Job-Level Permissions

Add job-specific permissions for workflows that need elevated access.

### When to Add Job Permissions:
- Steps using `secrets.GITHUB_TOKEN` or `github.token`
- Steps requiring write access (pushes, releases, deployments)

### Job Permission Rules:
1. **Placement**: Insert as the first child of the job YAML block
2. **Don't include `contents: read`** in job-level permissions
3. **Don't reorder existing blocks**
4. **Preserve existing `contents: read`** if already present

### Common Permission Patterns:
- `JamesIves/github-pages-deploy-action` → needs `contents: write`
- Writing to repository → needs `contents: write`
- Creating releases → needs `contents: write`
- Posting comments → needs `issues: write` or `pull-requests: write`

## ⚠️ Important Exceptions:
- **Steps which use `OPENTELEMETRYBOT_GITHUB_TOKEN`**: Custom tokens don't need workflow permissions
- **Steps which use `actions/cache/save`**: Doesn't require special permissions
- **Don't add unnecessary permissions**: Only add what's actually needed

## 📝 Implementation Guidelines:
- Read each file completely before making changes
- Only modify what's necessary for security compliance
- Maintain existing code style and formatting
- Don't add comments to the workflow files
- No need to test locally (workflows don't run in local builds)
